language: node_js
node_js:
  - 8
sudo: false
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run $HOME/node_modules/@uxpin/merge-cli/bin/uxpin-mergee --webpack-config ./webpack.config.uxpin.js --wrapper ./tools/UXPinWrapper.js