language: node_js
node_js:
  - 8
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test
  - npm run "uxpin-merge --webpack-config ./webpack.config.uxpin.js --wrapper ./tools/UXPinWrapper.js --uxpin-domain merge.uxpin.cloud"
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      git config --global user.name "Grommet Community Bot"
      git config --global user.email "grommet@hpe.com"
      npm run build && npm run release-stable
    fi
