language: node_js
node_js:
  - 8
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run "uxpin-merge --webpack-config ./webpack.config.uxpin.js --wrapper ./tools/UXPinWrapper.js --uxpin-domain merge.uxpin.cloud"
  - |
