language: node_js
node_js:
  - 8
sudo: false
before_install:
  - export PATH="$HOME"
install:
  - npm install
script:
  - npm run $HOME/node_modules/.bin/uxpin-merge --webpack-config ./webpack.config.uxpin.js --wrapper ./tools/UXPinWrapper.js
  - |
