version: 2

jobs:
  build:
    docker:
      - image: cypress/browsers:chrome69
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cypress-cache-{{ checksum "yarn.lock" }}
      - run: npm install
      - save_cache:
          key: yarn-cypress-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
      - run:
          name: Running linter
          command: npm run lint
      - run:
          name: Running jest
          command: npm run test
      - run:
          name: Running E2E tests
          command: npm run e2e
      - store_test_results:
          path: cypress/screenshots/diff
      - store_artifacts:
          path: cypress/screenshots/diff
          destination: cypress-diff
